spring.application.name=baggio-lighting-backend
server.port=9090
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.flyway.enabled=${FLYWAY_ENABLED:true}
spring.jackson.default-property-inclusion=non_null
