spring.application.name=baggio-lighting-backend
server.port=9090
spring.datasource.url=jdbc:mysql://localhost:3306/lighting_factory?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=baggio
spring.datasource.password=Bagggio@2026
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=${FLYWAY_ENABLED:true}
spring.jackson.default-property-inclusion=non_null
